"""
doc_generator.py

Turns the agent's planned sections + generated content into a polished
.docx file using python-docx (chosen over docx-js/pandoc since the whole
deliverable is a Python service and python-docx has zero external
dependencies beyond pip).
"""
import os
import re
import uuid
from datetime import datetime
from typing import Dict, List, Tuple

from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "outputs")
os.makedirs(OUTPUT_DIR, exist_ok=True)

ACCENT_COLOR = RGBColor(0x1F, 0x4E, 0x79)


def _set_cell_shading(cell, hex_color: str):
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = tc_pr.makeelement(qn("w:shd"), {
        qn("w:val"): "clear",
        qn("w:color"): "auto",
        qn("w:fill"): hex_color,
    })
    tc_pr.append(shd)


def _add_bullets_or_paragraphs(doc: Document, text: str):
    """
    If the generated text looks like a numbered/bulleted list (lines
    starting with '- ', '* ', or 'N.'), render as a Word bullet list.
    Otherwise render as normal paragraphs (split on newlines).
    """
    lines = [ln.strip() for ln in text.split("\n") if ln.strip()]
    list_pattern = re.compile(r"^(\-|\*|\d+[\.\)])\s+")

    if len(lines) > 1 and sum(1 for ln in lines if list_pattern.match(ln)) >= max(1, len(lines) // 2):
        for ln in lines:
            clean = list_pattern.sub("", ln)
            p = doc.add_paragraph(clean, style="List Bullet")
            p.paragraph_format.space_after = Pt(4)
    else:
        for ln in lines:
            p = doc.add_paragraph(ln)
            p.paragraph_format.space_after = Pt(8)
            for run in p.runs:
                run.font.size = Pt(11)


def build_docx(
    document_type: str,
    title: str,
    sections: Dict[str, str],
    assumptions: List[str],
) -> Tuple[str, str]:
    """
    Builds the .docx file and returns (filename, full_filepath).
    """
    doc = Document()

    # base typography
    normal = doc.styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(11)

    # ---------------- Title block ----------------
    title_p = doc.add_paragraph()
    title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title_p.add_run(title)
    run.font.size = Pt(24)
    run.font.bold = True
    run.font.color.rgb = ACCENT_COLOR

    subtitle_p = doc.add_paragraph()
    subtitle_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub_run = subtitle_p.add_run(
        f"{document_type.replace('_', ' ').title()}  |  Generated {datetime.now().strftime('%d %b %Y, %H:%M')}"
    )
    sub_run.font.size = Pt(11)
    sub_run.font.italic = True
    sub_run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    doc.add_paragraph()  # spacer

    # ---------------- Assumptions box (if any) ----------------
    if assumptions:
        note_heading = doc.add_paragraph()
        note_run = note_heading.add_run("Agent Assumptions & Notes")
        note_run.font.bold = True
        note_run.font.size = Pt(12)
        note_run.font.color.rgb = ACCENT_COLOR

        table = doc.add_table(rows=len(assumptions), cols=1)
        table.alignment = WD_TABLE_ALIGNMENT.CENTER
        for i, assumption in enumerate(assumptions):
            cell = table.rows[i].cells[0]
            cell.text = f"• {assumption}"
            _set_cell_shading(cell, "F2F6FA")
            for p in cell.paragraphs:
                for r in p.runs:
                    r.font.size = Pt(10)
        doc.add_paragraph()

    # ---------------- Sections ----------------
    for section_name, content in sections.items():
        heading = doc.add_heading(level=1)
        h_run = heading.add_run(section_name)
        h_run.font.color.rgb = ACCENT_COLOR
        h_run.font.size = Pt(15)

        _add_bullets_or_paragraphs(doc, content)
        doc.add_paragraph()

    # ---------------- Footer ----------------
    doc.add_paragraph()
    footer_p = doc.add_paragraph()
    footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer_p.add_run("Generated by Agent")
    footer_run.font.size = Pt(9)
    footer_run.font.italic = True
    footer_run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)

    safe_title = re.sub(r"[^a-zA-Z0-9]+", "_", title)[:40].strip("_") or document_type
    filename = f"{safe_title}_{uuid.uuid4().hex[:8]}.docx"
    filepath = os.path.join(OUTPUT_DIR, filename)
    doc.save(filepath)

    return filename, filepath
